const formInputs = [
  {
    labelname: "ГЭРЭЭНИЙ ДУГААР",
    pathname: "contractNumber",
    type: "text",
    isRequired: 1,
  },
  {
    labelname: "ОН САР",
    pathname: "date",
    type: "date",
    isRequired: 1,
  },
  {
    labelname: "ОВОГ",
    pathname: "lastName",
    type: "text",
    isRequired: 1,
  },
  {
    labelname: "НЭР",
    pathname: "customerName",
    type: "text",
    isRequired: 1,
  },
  {
    labelname: "РЕГИСТР",
    pathname: "positionName",
    type: "text",
    isRequired: 1,
  },
  {
    labelname: "ТӨРСӨН ОГНОО",
    pathname: "dateOfBirth",
    type: "date",
    isRequired: 1,
  },
  {
    labelname: "ХҮЙС",
    pathname: "gender",
    type: "combo",
    name: "name",
    lookupId: "1448432578544",
    isRequired: 1,
  },
  {
    labelname: "Гадаад хүн эсэх",
    pathname: "citizen",
    type: "hidden",
    isRequired: 1,
  },
  {
    labelname: "Насанд хүрсэн эсэх",
    pathname: "isAdult",
    type: "hidden",
    isRequired: 1,
  },
  {
    labelname: "Нууц үг",
    pathname: "password",
    type: "hidden",
    isRequired: 1,
  },
  {
    labelname: "Картын дугаар",
    pathname: "cardNumber",
    type: "hidden",
    isRequired: 1,
  },
  {
    labelname: "УТАС",
    pathname: "phoneNumber",
    type: "number",
    isRequired: 1,
  },
  {
    labelname: "И-МЭЙЛ",
    pathname: "EMAIL",
    type: "email",
    isRequired: 1,
  },
  {
    labelname: "ХОТ",
    pathname: "cityId",
    type: "combo",
    lookupId: "1448415981113",
    name: "cityname",
    isRequired: 1,
  },
  {
    labelname: "ДҮҮРЭГ",
    pathname: "districtId",
    type: "combo",
    lookupId: "144436175673444",
    criteriaPath: "cityId",
    name: "name",
    isRequired: 1,
  },
  {
    labelname: "ХОРОО",
    pathname: "streetId",
    type: "combo",
    lookupId: "1448415981268",
    criteriaPath: "districtId",
    name: "streetname",
    isRequired: 1,
  },
];

export default formInputs;
